### ISSUE TITLE
Tokens without USD value

### ISSUE THREAD

**Issue by Ran73Cohen** [bancorprotocol/webapp-v2#130]
- [ ] USD value for tokens that dont exist in the rate API (should be very edge case)
for tokens that dont have USD value, we should use the bancor rate to calculate this. 
USD value of the token = 2nd token $Value * (spot rate between 2nd token to 1st token. we use this calculation for price impact)
example = $4191 * (1/572.3) = 1 unit of 1st token = $7.3230823
![image](https://user-images.githubusercontent.com/40430285/126469469-5a20e9a2-87b4-4c37-bbd6-a3c4e168bb3d.png)
![image](https://user-images.githubusercontent.com/40430285/126469690-95307048-8f8a-4b17-a782-69e2b5935048.png)

**Comment by ashachaf** [comment]
cannot reproduce
