### ISSUE TITLE
token search modal

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#221]
on the token search modal, some tokens have long name that are not supported and are currently cut.

please handle in this way:
1. increase supported token name length to 25 characters
2. IF token name is GREATER than 25, 
- hide the last 3 characters of the token name
- replace them with ```...```
- implement text overflow ellipsis marquee
(https://stackoverflow.com/questions/41987383/how-to-make-marquee-text-only-when-its-overflowing)

**Comment by pingustar** [comment]
This is a limitation of the token list, we can not increase it to 25 because the token list returns names with max 19 characters.

I can add the `...` to any token that has a length of 19 characters instead.
