### ISSUE TITLE
Notifications on mobile wallet

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#253]
as a user, when i execute a trade using a mobile wallet (metamask), i would like the notifications to be managed correctly

1. when they appear, they should be over (above) the top bar and not hidden behind it
2. when i try to click on the x, it should close the popup

![image](https://user-images.githubusercontent.com/40430285/129024045-6d35de84-52d7-4352-aa59-45115e380cc5.png)

**Comment by Ran73Cohen** [comment]
https://github.com/bancorprotocol/webapp-v2/pull/279
