### ISSUE TITLE
Token search modal - web functionality 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#256]
as a user, when i open the token search modal on the convert widget, i am able to search for a specific token.
when entering search values, the modal shrinks vertically instead of staying in the same vertical top position and only shrink the bottom part.

flow:
1. open convert
2. click "select a token"
3. search 
expected -> top position should stay as is and the bottom part should shrink upwards

current:
default modal:
![image](https://user-images.githubusercontent.com/40430285/129189689-b39f9261-6f24-479f-95d9-a0dda95bc250.png)

search -> modal shrinks to the center:
![image](https://user-images.githubusercontent.com/40430285/129189721-af09ef99-f1f2-4f4a-a526-0b7107ea64c4.png)

**Comment by baart1989** [comment]
Hello @ashachaf 
Would this be acceptable solution ?

![Screenshot 2021-08-12 at 14 15 57](https://user-images.githubusercontent.com/6317798/129195086-69b04180-6afe-4f81-99f9-418ccdd78856.png)

**Comment by ashachaf** [comment]
yes

**Comment by ashachaf** [comment]
> Hello @ashachaf
> Would this be acceptable solution ?
> 
> ![Screenshot 2021-08-12 at 14 15 57](https://user-images.githubusercontent.com/6317798/129195086-69b04180-6afe-4f81-99f9-418ccdd78856.png)

Yes that could work as well.
