### ISSUE TITLE
empty pools - insufficient funds indication

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#268]
as a user, when the token path goes via a pool with no liquidity, the trade widget should indicate that there is insufficient balance for the trade.

flow
if token rate = 0,
OR
if slippage > 50%
-> indicate "Insufficient liquidity" and disable the option to execute the trade.

example:
1. open the trade widget
2. select ETH -> REQ
expected to see an indication that there is insufficient balance.

**Comment by RanCohenn** [comment]
Stale
