### ISSUE TITLE
Notifications on mobile

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#273]
related to #253 

on mobile, we need to increase the size of the area that close the notification.
when clicking on the area marked in red, this should close the notification.

![image](https://user-images.githubusercontent.com/40430285/129677759-1a1b0b12-66d1-4451-8072-bddfc2bf85d3.png)

**Comment by Ran73Cohen** [comment]
https://github.com/bancorprotocol/webapp-v2/pull/279
