### ISSUE TITLE
Notification - incorrect notification on mobile

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#274]
tested on metamask mobile app
(on web, it seems to work correctly)
flow:
1. browse to beta.bancor.network
2. set a trade
3. click "trade"
4. see the confirmation screen
5. reject
expected: see the "transaction rejected" notification
actual:
![image](https://user-images.githubusercontent.com/40430285/129678745-f52bdc86-8be4-4e92-b6de-9564da18fc55.png)

**Comment by baart1989** [comment]
@ashachaf  i think this one can be closed?

**Comment by ashachaf** [comment]
on mobile, when a user rejected the transaction on his wallet, we showed "transaction failed" notification instead of "transaction rejected" one.

now, it seems that there are no notifications on mobile.
@Ran73Cohen

**Comment by baart1989** [comment]
to my mind it is different problem now, most likely just z-index attribute that needs increasing

**Comment by RanCohenn** [comment]
Stale
