### ISSUE TITLE
tokens page (table) - update ticker behavior 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#305]
as a user, when i click on the ticker item, i would like the token at hand would be selected in the table below.

flow
1. go to https://beta.bancor.network/tokens
2. click on any token in the ticker
expected: input the token symbol to the search box in the table below in order to show the token i wanted to focus on

(reference: https://beta.bancor.network/pools have such functionality)

**Comment by adarshram** [comment]
I would like to take this issue up .
