### ISSUE TITLE
limit order - token not supported indication

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#313]
update CTA to indicate token not supported

when a user selects a token on market and then switch to limit, please do the following:
- IF the token exists on the token list (in this case the limit order token list) -> proceed normally
- ELSE (token is not on the list) -> update the CTA:
- [ ] disable the CTA
- [ ] identify which of the tokens is not supported (from or to) and save the token symbol as {token}
- [ ] update text: "{token} is not supported"

**Comment by Ran73Cohen** [comment]
Solved in #286
