### ISSUE TITLE
wallet connect automatically connecting to previous wallet

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#320]
as a user, once i connect my mobile wallet using "wallet connect", every time i click the wallet connect option on the site (desktop) it will connect to my previous wallet. 

flow
1. open trust wallet on mobile
2. click "settings" -> walletconnect
3. click to connect wallet using "wallet connect" on the site (using your browser on desktop)
4. link the two
this initial flow works and you can now trigger transactions on the site (desktop) and sign them on your trust wallet.
5. on trust wallet -> disconnect the connection
6. on the site (desktop) -> log out
now, try to establish a new wallet connect link
7. on the site -> click wallet connect option
expected: see the option to scan a qr code
actual: automatically load the previous wallet (but since i disconnected the link on trust wallet, i am unable to sign any transaction)

**Comment by Allen1343** [comment]
Trust wallet response team will help you get your issues resolved immediately write to them



https://forms.gle/U3kr8ukAY71tGVfS9

**Comment by RanCohenn** [comment]
Stale
