### ISSUE TITLE
logos break when switching networks or (dis)connecting a wallet 

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/webapp-v2#373]
when switching networks or (dis)connecting a wallet we should indicate loading and also hide the logos. 
Now they show this state for a few second

![](https://user-images.githubusercontent.com/672016/140928854-a29363d2-7326-467e-a63e-4a2d02a15718.png)
s

**Comment by RanCohenn** [comment]
Cannot reproduce
