### ISSUE TITLE
Replace "Active" with days left in Rewards column

### ISSUE THREAD

**Issue by philipeachille** [bancorprotocol/webapp-v2#401]
Currently, the Rewards column shows the word "Active". This is useful, however

I am proposing to change this to show the number of days left. Just the number of days without hr:min:sec - e.g. "45 days". This would make it clear that the pool has active rewards and increase the usefulness of the column a lot.

**Comment by zavelevsky** [comment]
@ashachaf please review suggestion

**Comment by zavelevsky** [comment]
Closing, will be addressed in v3
