### ISSUE TITLE
portfolio - pool tokens

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#413]
as a user, i would like to be able to see my pool tokens on the portfolio.

it seems that this pool token is NOT visible:
0x4b51acc819591c885dba0f06d98a07b432e6d6b4

this anchor appears in the registry and api.
we might not show it because it is not in coingecko tokenlist HOWEVER, we should NOT restrict to show only tokens on the tokenlist in this case.

**Comment by pingustar** [comment]
when using a mocked user account, I can see the pool token balance in the table

![telegram-cloud-photo-size-1-4965478435153619288-y](https://user-images.githubusercontent.com/7262066/142992776-17dfe60e-25e1-41b5-8ddf-fa6cef937f03.jpg)
