### ISSUE TITLE
Adding liquidity fails with "Transaction Failed"

### ISSUE THREAD

**Issue by primalglenn** [bancorprotocol/webapp-v2#424]
See the error below, this is on the DyDx pool but I have seen similar error reports from other folks. Is there something broken on our end?

![image](https://user-images.githubusercontent.com/1395788/142714312-ed66a8c5-d8d2-4f8c-8e3c-3b6ee606172d.png)

**Comment by primalglenn** [comment]
Another example for $TRAC pool 

![image](https://user-images.githubusercontent.com/1395788/142714449-bd744ca4-85d8-4c35-93e0-bd0f9a54fd84.png)

**Comment by primalglenn** [comment]
Seems to be failing on my end because:

"MetaMask - RPC Error: execution reverted: ERC20: transfer amount exceeds allowance {code: -32603, message: 'execution reverted: ERC20: transfer amount exceeds allowance', data: {…}}"

But I have unlimited approval for this token granted on the standard pool converter (0xa4b17a0879f8fb9cecde38850f1545be20582f87)

![image](https://user-images.githubusercontent.com/1395788/142714778-077ea898-7c97-49c2-914b-776f5c532e93.png)

Maybe I also need the unlimited approval on the liquidityprotection contract (0x853c2d147a1bd7eda8fe0f58fb3c5294db07220e)? But why isn't the UI prompting me for it if that's the case?

**Comment by primalglenn** [comment]
>Maybe I also need the unlimited approval on the liquidityprotection contract (0x853c2d147a1bd7eda8fe0f58fb3c5294db07220e)? But why isn't the UI prompting me for it if that's the case?

This was the issue and I had to do this manually. We should fix this in the UI.

**Comment by primalglenn** [comment]
The workaround is to find the address of the token that you are looking to deposit (you can use coingecko/cmc for this). Go to etherscan for that token (replace question marks with the token address):

https://etherscan.io/token/0x???????????????????????????????????????????#writeContract

1. under the write contract tab > select the "Connect to Web3" button > connect your wallet
2. Expand the "approve" function:

For "_Spender(Address)" type in "0x853c2d147a1bd7eda8fe0f58fb3c5294db07220e"
For "_value (uint 256)" type in "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" (this is for unlimited approval)

3. Select the write button to send the TX
4. Go back to the "bancor.network" site to stake your tokens

**Comment by RanCohenn** [comment]
@primalglenn Thank you for opening an issue and investigating it so thoroughly!
The code was indeed approving the wrong contract and was changed to approve the correct one
