### ISSUE TITLE
Portfolio - incorrect multiplier 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#426]
https://docs.google.com/document/d/19LKZo2ylqOygOR5EXnyDzpm3zucJGiyQLUQdauJ9S6k/edit#

**Comment by RanCohenn** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp-v2/commit/aaa820f4287012ea757230af53821d2cd5db67d4)
