### ISSUE TITLE
WalletConnect "stake and protect" does nothing

### ISSUE THREAD

**Issue by primalglenn** [bancorprotocol/webapp-v2#452]
I can successfully connect via WalletConnect to the Bancor site without any issues. When trying to stake a token, clicking on the "stake and protect" button:

![image](https://user-images.githubusercontent.com/1395788/143497555-3bb19466-bacd-4210-954e-44aad8365e63.png)
 
does not prompt me for approval (it does nothing).

**Comment by RanCohenn** [comment]
@primalglenn I cannot reproduce this issue, could you upload an image\error text from your console?

**Comment by syl3ntz** [comment]
[app.bancor.network-1638369555502.log](https://github.com/bancorprotocol/webapp-v2/files/7634858/app.bancor.network-1638369555502.log)
Clicking Swap or Stake returns nothing

**Comment by syl3ntz** [comment]
[app.bancor.network.zip](https://github.com/bancorprotocol/webapp-v2/files/7634862/app.bancor.network.zip)
HAR file

**Comment by primalglenn** [comment]
@RanCohenn 

Take a look at the GIF that I attached here to see what's happening. Note that I am using android with trustwallet and connecting via wallet connect.

![busted_wallet_connect](https://user-images.githubusercontent.com/1395788/145156023-683e40e5-5c32-4b7b-8557-78ae76544f29.gif)

Errors on console are the following and it looks like @syl3ntz also included a HAR file for reference

```
Access to XMLHttpRequest at 'wss://eth-mainnet.ws.alchemyapi.io/v2/m2607P4kbMyyrp3VFeEThvhlV9s8hzTf' from origin 'https://app.bancor.network' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
wss://eth-mainnet.ws.alchemyapi.io/v2/m2607P4kbMyyrp3VFeEThvhlV9s8hzTf:1 Failed to load resource: net::ERR_FAILED
0.08e11f90.chunk.js:1 Uncaught Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at r.<anonymous> (/static/js/0.08e11f90.chunk.js:1)
    at l (3.32ed6b23.chunk.js:1)
    at Generator._invoke (3.32ed6b23.chunk.js:1)
    at Generator.throw (3.32ed6b23.chunk.js:1)
    at r (3.32ed6b23.chunk.js:1)
    at u (3.32ed6b23.chunk.js:1)
0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533:1 Access to XMLHttpRequest at 'wss://eth-mainnet.ws.alchemyapi.io/v2/m2607P4kbMyyrp3VFeEThvhlV9s8hzTf' from origin 'https://app.bancor.network' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
wss://eth-mainnet.ws.alchemyapi.io/v2/m2607P4kbMyyrp3VFeEThvhlV9s8hzTf:1 Failed to load resource: net::ERR_FAILED
0.08e11f90.chunk.js:1 Uncaught Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at r.<anonymous> (0.08e11f90.chunk.js:1)
    at l (3.32ed6b23.chunk.js:1)
    at Generator._invoke (3.32ed6b23.chunk.js:1)
    at Generator.throw (3.32ed6b23.chunk.js:1)
    at r (3.32ed6b23.chunk.js:1)
    at u (3.32ed6b23.chunk.js:1)
```
