### ISSUE TITLE
Portfolio - use token image placeholder if image is not available

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#467]
when we load the portfolio table, if an image is missing (no image, not on the enabled token list), use a default token placeholder image.

flow:
1. visit portfolio
2. load a token that is not on the enabled tokenlist
expected - load the table with data, display all tokens even if they are not on the tokenlist, user token place holder if needed.
actual - load get stuck.

**Comment by pingustar** [comment]
@ashachaf is there a token and list to reproduce this with? Not sure I understand the issue.

If no token image is provided, it should fall back to the grey eth image (as we use on ropsten)

**Comment by ashachaf** [comment]
on mainnet:
1. go to "trade"
2. click "select a token" 
3. click "manage token lists"
4. keep only a list with very little tokens 
5. go to portfolio and check if it loads (you would need to have few positions)

on ropsten:
you would need to remove few tokens from the list we maintain as the "token list"
