### ISSUE TITLE
Unstake $vBNT from governance button is never active...timer is broken  

### ISSUE THREAD

**Issue by primalglenn** [bancorprotocol/webapp-v2#482]
My last $vBNT stake into the governance contract was 3 days and 7 hours ago. I had the following time remaining when I checked yesterday:

![vbnt](https://user-images.githubusercontent.com/1395788/146417329-ad75c8e0-a0b4-4d96-af6b-37899355340e.PNG)

When I checked today, the timer has reset and has gone up:

![image](https://user-images.githubusercontent.com/1395788/146416974-dd596b8b-85ad-468c-b108-5fc1d3d78c46.png)

There is something busted in the logic of the unstaking button.

**Comment by ashachaf** [comment]
@pingustar can you have a look?
