### ISSUE TITLE
URL redirect - swap.bancor.network

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#486]
please update the redirect logic to this URL destination.

swap.bancor.network -> 
current redirect: https://app.bancor.network/swap/ (which is a 404 page)
updated redirect: https://app.bancor.network/ (the trade page)

**Comment by zavelevsky** [comment]
Fixed URL forwarding, validated with devtools open - but otherwise browsers will take some time getting the change.
