### ISSUE TITLE
Add liquidity to old pools

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#500]
similar to issue #496 
older pool converters support different functions for adding and removing liquidity.

reproduce:
1. open pools table
2. search for USDB
3. try to add liquidity
4. see this error
![image](https://user-images.githubusercontent.com/40430285/148370031-54e2bc64-bd32-433a-80d5-23f6f36b0bdc.png)

reason ( i think):
this is an old converter and the function to add liquidity is called "fund"
https://etherscan.io/address/0xe03374cacf4600f56bddbdc82c07b375f318fc5c#writeContract

this function requires different values to be passed in it.

unlike the "addLiquidity" function
https://etherscan.io/address/0x90c048f8ef5a135b77bce450fc36b7cb593e519b#writeContract

**Comment by pingustar** [comment]
@ashachaf based on our conversation, we will change the objective of this issue to:

- not support 'Add Liquidity' for pools with version < 28
- remove pools from Pool Table with version < 28

'Remove liquidity' for pools with version < 28 will be available in the Portfolio -> Pool Tokens tab
