### ISSUE TITLE
adding liquidity - incorrect BNT amount needed to open up space 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#525]
https://app.bancor.network/pools/add-liquidity/0x10c301D7968a743bb3dee90fB4A694C9c00E78A2

![image](https://user-images.githubusercontent.com/40430285/151706335-68ecb676-0993-47ad-8177-0342a1950dcf.png)

when clicking the amount of BNT needed:
![image](https://user-images.githubusercontent.com/40430285/151706347-aee38b25-ffca-4b0b-bc44-bf2501d23094.png)

referrence:
https://github.com/bancorprotocol/webapp/issues/775

**Comment by pingustar** [comment]
currently not reproducible, will monitor it for a bit and see if it happens again

**Comment by pingustar** [comment]
closing. Issue not reproducible
