### ISSUE TITLE
GA fix

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#526]
![image](https://user-images.githubusercontent.com/40430285/151969594-1d985c7b-eafa-4b81-afef-98f04008ba1b.png)

current:
Conversion click
updated:
Conversion Swap Click
(FYI it used to be Conversion Swap Click before)

**Comment by pingustar** [comment]
hotfix to main in commit https://github.com/bancorprotocol/webapp-v2/commit/32467ccefc5c6f71e7013960c9ab2c60bb8c5161
