### ISSUE TITLE
disable claim/stake rewards CTA

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#553]
- [ ] please disable the claim/stake rewards CTA
add a tool tip when mouse over these CTA: "Rewards were disabled as part of the V3 upgrade and will be available again shortly"
<img width="521" alt="image" src="https://user-images.githubusercontent.com/40430285/167571474-80ce8aea-807d-4d8b-9392-0b6330ee5f49.png">

- [ ] remove the stake CTA from the group level

**Comment by zavelevsky** [comment]
I plan to also fix this
/portfolio/rewards/claim

<img width="495" alt="image" src="https://user-images.githubusercontent.com/672016/167585534-78f8a1b8-b8ac-4ea1-81b1-bfbdc61d399b.png">
