### ISSUE TITLE
add liquidity URL redirect

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v2#72]
as a user, if the pool supports single side i would like to always be able to stake single side liquidity even when i open dual side page somehow.

process:
1. open dual side liquidity staking directly: https://app.bancor.network/eth/pool/add/0x3E22d87977dA52Accef2Af9Eb50f76bd31b7b6B1

expected flow:
1. when a user visit the "dual side" add liquidity page
2. check if the pool is white listed
3. if YES -> redirect to the single side staking page

**Comment by RanCohenn** [comment]
Stale
